# Generated by Django 5.1.7 on 2025-04-05 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_repairproduct_servicerequest_servicestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.ForeignKey(limit_choices_to={'category': 'repair_service'}, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Repair Service Type'),
        ),
    ]
