# Generated by Django 5.1.7 on 2025-04-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_servicerequest_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_type',
        ),
    ]
